import argparse
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from prometheus.analysis.eclipse_validator import derive_pillar_rows, summarize_pillars
from prometheus.main import Prometheus


def _safe(v, default: float = 0.0) -> float:
    try:
        if v is None:
            return default
        return float(v)
    except Exception:
        return default


def _metric_pack(result) -> Dict[str, float]:
    return {
        "trades": int(getattr(result, "total_trades", 0) or 0),
        "win_rate": _safe(getattr(result, "win_rate", 0.0), 0.0),
        "pf": _safe(getattr(result, "profit_factor", 0.0), 0.0),
        "sharpe": _safe(getattr(result, "sharpe_ratio", 0.0), 0.0),
        "calmar": _safe(getattr(result, "calmar_ratio", 0.0), 0.0),
        "max_dd": _safe(getattr(result, "max_drawdown_pct", 0.0), 0.0),
        "ret": _safe(getattr(result, "total_return_pct", 0.0), 0.0),
    }


def _status(base: float, target: float, higher_better: bool) -> str:
    if higher_better:
        return "PASS" if target >= base else "FAIL"
    return "PASS" if target <= base else "FAIL"


def _run_slice(prom: Prometheus, data_intra, data_daily, symbol: str, override: Optional[Dict]):
    result, engine = prom._run_intraday_backtest_on_slice(
        data_slice=data_intra,
        data_daily=data_daily,
        symbol=symbol,
        bar_interval="5minute",
        strategy_name="eclipse_eval",
        parrondo=True,
        dd_throttle=True,
        vol_target=0.0,
        equity_curve_filter=False,
        half_capacity_mode=False,
        equity_ma_sizing=False,
        dsq_filter=False,
        param_overrides=override,
        verbose=False,
    )
    return result, engine


def _write_csv(path: Path, headers: List[str], rows: List[List]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(headers)
        w.writerows(rows)


def _write_yaml(path: Path, symbol_rows: Dict[str, Dict]):
    lines = [
        "# Auto-generated by run_eclipse_guard.py",
        f"generated_at: {datetime.now().isoformat(timespec='seconds')}",
        "policy: eclipse_intraday_strict",
        "symbols:",
    ]

    whitelist = []
    for sym, meta in symbol_rows.items():
        if not meta.get("allow", False):
            continue
        whitelist.append(sym)
        lines.extend(
            [
                f"  \"{sym}\":",
                "    trade_enabled: true",
                f"    max_position_risk_pct: {meta['max_position_risk_pct']:.2f}",
                f"    max_daily_loss_pct: {meta['max_daily_loss_pct']:.2f}",
                f"    max_concurrent_positions: {int(meta['max_concurrent_positions'])}",
            ]
        )

    if not whitelist:
        lines.append("  {}")

    lines.append("symbol_whitelist:")
    for sym in whitelist:
        lines.append(f"  - \"{sym}\"")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="ECLIPSE intraday A/B guard with pillar attribution")
    parser.add_argument("--symbols", nargs="+", default=["NIFTY 50", "NIFTY BANK"], help="Symbols to evaluate")
    parser.add_argument("--days", nargs="+", type=int, default=[30, 59], help="Intraday windows in days")
    parser.add_argument("--data-source", default="yfinance", choices=["auto", "yfinance", "angelone"], help="Historical source")
    parser.add_argument("--fetch-retries", type=int, default=2, help="Historical fetch retries")
    parser.add_argument("--output-root", default="regression/eclipse_guard", help="Output directory")
    args = parser.parse_args()

    eclipse_override = {
        "trendday_prefilter": True,
        "confluence_trending": 2.7,
        "target_atr_mult": 2.2,
        "time_stop_bars": 16,
        "fixed_premium_sl_enabled": True,
        "fixed_premium_sl_pct": 0.20,
        "dead_zone_start": "12:00",
        "dead_zone_end": "13:00",
        "use_second_window": True,
        "allow_counter_bias_when_strong": False,
        "counter_bias_min_net_edge": 2.6,
        "vol_adaptive_trailing": True,
        "event_risk_gate_enabled": False,
        "symbol_overrides": {
            "NIFTY 50": {
                "trendday_persistence_min": 0.50,
                "orb_atr_buffer": 0.07,
                "trendday_breakout_override_atr": 0.70,
            },
            "NIFTY BANK": {
                "trendday_persistence_min": 0.40,
                "orb_atr_buffer": 0.03,
                "trendday_breakout_override_atr": 0.45,
            },
        },
    }

    baseline_override = {
        "trendday_prefilter": False,
        "confluence_trending": 2.8,
        "target_atr_mult": 2.2,
        "time_stop_bars": 14,
        "fixed_premium_sl_enabled": True,
        "fixed_premium_sl_pct": 0.20,
        "dead_zone_start": "11:30",
        "dead_zone_end": "13:30",
        "use_second_window": True,
        "allow_counter_bias_when_strong": False,
        "counter_bias_min_net_edge": 2.5,
        "vol_adaptive_trailing": True,
        "event_risk_gate_enabled": False,
    }

    prom = Prometheus(config_path="prometheus/config/settings.yaml")
    prom.data.configure_historical_fetch(source=args.data_source, retries=args.fetch_retries)
    # Keep deterministic/fail-open behavior for VIX during comparative backtests.
    prom.data.get_vix = lambda: 15.0

    out_root = Path(args.output_root) / datetime.now().strftime("%Y%m%d_%H%M%S")
    out_root.mkdir(parents=True, exist_ok=True)

    metric_rows: List[List] = []
    pillar_rows: List[Dict] = []

    symbol_pass: Dict[str, List[bool]] = {s: [] for s in args.symbols}
    symbol_dd: Dict[str, float] = {s: 0.0 for s in args.symbols}

    for symbol in args.symbols:
        for days in args.days:
            data_intra = prom.data.fetch_historical(symbol, days=days, interval="5minute", force_refresh=False)
            data_daily = prom.data.fetch_historical(symbol, days=max(days, 120), interval="day", force_refresh=False)

            b_res, b_eng = _run_slice(prom, data_intra, data_daily, symbol, baseline_override)
            e_res, e_eng = _run_slice(prom, data_intra, data_daily, symbol, eclipse_override)

            b = _metric_pack(b_res)
            e = _metric_pack(e_res)

            pf_status = _status(b["pf"], e["pf"], True)
            sh_status = _status(b["sharpe"], e["sharpe"], True)
            ca_status = _status(b["calmar"], e["calmar"], True)
            dd_status = _status(b["max_dd"], e["max_dd"], False)
            trade_status = "PASS" if e["trades"] >= 4 else "FAIL"
            row_pass = all(x == "PASS" for x in [pf_status, sh_status, ca_status, dd_status, trade_status])
            symbol_pass[symbol].append(row_pass)
            symbol_dd[symbol] = max(symbol_dd[symbol], e["max_dd"])

            metric_rows.append([
                symbol,
                days,
                round(b["pf"], 4),
                round(e["pf"], 4),
                pf_status,
                round(b["sharpe"], 4),
                round(e["sharpe"], 4),
                sh_status,
                round(b["calmar"], 4),
                round(e["calmar"], 4),
                ca_status,
                round(b["max_dd"], 4),
                round(e["max_dd"], 4),
                dd_status,
                int(e["trades"]),
                trade_status,
                "PASS" if row_pass else "FAIL",
            ])

            pillar_rows.extend(derive_pillar_rows(b_res.trades, "baseline", symbol, days))
            pillar_rows.extend(derive_pillar_rows(e_res.trades, "eclipse", symbol, days))

    metric_csv = out_root / "intraday_ab_no_degrade.csv"
    _write_csv(
        metric_csv,
        [
            "Symbol",
            "Days",
            "Base_PF",
            "Eclipse_PF",
            "PF_Status",
            "Base_Sharpe",
            "Eclipse_Sharpe",
            "Sharpe_Status",
            "Base_Calmar",
            "Eclipse_Calmar",
            "Calmar_Status",
            "Base_MaxDD",
            "Eclipse_MaxDD",
            "MaxDD_Status",
            "Eclipse_Trades",
            "TradeCount_Status",
            "Row_Status",
        ],
        metric_rows,
    )

    pillar_csv = out_root / "pillar_trade_attribution.csv"
    if pillar_rows:
        headers = list(pillar_rows[0].keys())
        _write_csv(pillar_csv, headers, [[r.get(h, "") for h in headers] for r in pillar_rows])
    else:
        _write_csv(pillar_csv, ["profile", "symbol", "days"], [])

    eclipse_rows = [r for r in pillar_rows if r.get("profile") == "eclipse"]
    pillar_summary = summarize_pillars(eclipse_rows)

    summary_json = out_root / "pillar_summary.json"
    summary_json.write_text(json.dumps(pillar_summary, indent=2), encoding="utf-8")

    deploy_meta: Dict[str, Dict] = {}
    for symbol in args.symbols:
        allow = bool(symbol_pass[symbol]) and all(symbol_pass[symbol])
        max_dd = symbol_dd[symbol]
        if max_dd <= 20:
            risk_pct, day_loss, max_pos = 1.0, 3.0, 2
        elif max_dd <= 30:
            risk_pct, day_loss, max_pos = 0.8, 2.5, 1
        else:
            risk_pct, day_loss, max_pos = 0.6, 2.0, 1
        deploy_meta[symbol] = {
            "allow": allow,
            "max_position_risk_pct": risk_pct,
            "max_daily_loss_pct": day_loss,
            "max_concurrent_positions": max_pos,
        }

    deploy_yaml = Path("prometheus/config/eclipse_deployment_filters.yaml")
    _write_yaml(deploy_yaml, deploy_meta)

    print("ECLIPSE_GUARD_OUT_START")
    print(json.dumps({
        "output_dir": str(out_root),
        "metrics_csv": str(metric_csv),
        "pillar_csv": str(pillar_csv),
        "pillar_summary": str(summary_json),
        "deployment_filters": str(deploy_yaml),
    }, indent=2))
    print("ECLIPSE_GUARD_OUT_END")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
